---
- hosts: all
  tasks:
    - name: Register output
      shell: echo "$(hostname)"
      register: hostname_output

    - name: Register output
      shell: ntpq -p
      register: ntpq_output

    - local_action: file path=/tmp/ntpq.txt state=touch
    - local_action: lineinfile line="{{ ansible_hostname }} \n {{ hostname_output.stdout }} \n {{ ntpq_output.stdout }} \n"  insertafter=EOF dest=/tmp/ntpq.txt
