---
- hosts: all
  become: true
  tasks:
    - name: Register output
      shell: echo "$(ntpq -p)"
      register: ntpq_output

    - local_action: file path=/tmp/ntpq.txt state=touch
    - local_action: lineinfile line="{{ ansible_hostname }} \n {{ ntpq_output.stdout }} \n"  insertafter=EOF dest=/tmp/ntpq.txt
