---
- hosts: all
  tasks:
    - name: Register output
      shell: echo "$(ntpstat)"
      register: ntpstat_output

    - local_action: file path=/tmp/ntpstat.txt state=touch
    - local_action: lineinfile line="{{ ansible_hostname }} \n {{ ntpstat_output.stdout }} \n"  insertafter=EOF dest=/tmp/ntpstat.txt

