---

- hosts: all
  tasks:
    - name: Register output
      shell: echo "$(rpm -qa | grep puppet)"
      register: host_output

    - local_action: file path=/tmp/rpm_puppet.txt state=touch
    - local_action: lineinfile line="{{ ansible_hostname }} \n {{ host_output.stdout }} \n"   insertafter=EOF dest=/tmp/rpm_puppet.txt


