---

- hosts: all
  tasks:
    - name: Register output
      shell: echo "$(rpm -qa | grep puppet)"
      register: puppet_output

    - name: Register output
      shell: echo "$(rpm -qa | grep mcollective)"
      register: mcollective_output

    - name: Register output
      shell: echo "$(rpm -qa | grep pxp)"
      register: pxp_output

    - local_action: file path=/tmp/rpm_pup_agents_check.txt state=touch
    - local_action: lineinfile line="{{ ansible_hostname }} \n {{ puppet_output.stdout }} \n {{ mcollective_output.stdout }} \n {{pxp_output.stdout }} \n"   insertafter=EOF dest=/tmp/rpm_pup_agents_check.txt
